### ISSUE TITLE
Error al Instalar el modulo contract_sale 11.0

### ISSUE THREAD

**Issue by Vtejero** [OCA/contract#188] opened 2018-09-26 17:41 UTC
tengo el sigueinte error al intentar instalar el modulo contract_sale en odoo 11.

> Error:
> Odoo Server Error

> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
>     r = d[key]
>   File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
>     return func(self, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
>     a = self.d[obj].me
> KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f4129ae27b8>,
>  'contract.action_account_analytic_sale_overdue_all')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 465, in _tag_menuitem
>     action_type, action_id = self.model_id_get(a_action)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 733, in model_id_get
>     return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, 
> raise_if_not_found=raise_if_not_found)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
>     return self.xmlid_lookup(xmlid)[1:3]
>   File "<decorator-gen-21>", line 2, in xmlid_lookup
>   File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
>     raise ValueError('External ID not found in the system: %s' % xmlid)
> ValueError: External ID not found in the system: contract.action_account_analytic_sale_overdue_all
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 350, in safe_eval
>     return unsafe_eval(c, globals_dict, locals_dict)
>   File "", line 1, in <module>
>   File "<decorator-gen-42>", line 2, in button_immediate_install
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 449, in 
> button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 542, in 
> _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 791, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 852, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 751, in parse
>     exc_info[2]
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 465, in _tag_menuitem
>     action_type, action_id = self.model_id_get(a_action)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 733, in model_id_get
>     return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, 
> raise_if_not_found=raise_if_not_found)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
>     return self.xmlid_lookup(xmlid)[1:3]
>   File "<decorator-gen-21>", line 2, in xmlid_lookup
>   File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
>     raise ValueError('External ID not found in the system: %s' % xmlid)
> odoo.tools.convert.ParseError: "External ID not found in the system: 
> contract.action_account_analytic_sale_overdue_all" while parsing
> /opt/odoo/odoo11/addons/contract_sale/views/account_analytic_account_view.xml:10, near
> <menuitem id="menu_contract_sale" name="Contracts" parent="sale.sale_order_menu" 
> action="contract.action_account_analytic_sale_overdue_all" sequence="2" 
> groups="sales_team.group_sale_salesman"/>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1231, in run
>     result = request.env['ir.actions.server'].browse([action_id]).run()
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 554, in run
>     res = func(action, eval_context=eval_context)
>   File "/opt/odoo/odoo11/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
>     res = super(ServerAction, self).run_action_code_multi(action, eval_context)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 430, in run_action_code_multi
>     safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to
> return 'action'
>   File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 373, in safe_eval
>     pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), 
> expr)), exc_info[2])
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/odoo/odoo11/odoo/tools/safe_eval.py", line 350, in safe_eval
>     return unsafe_eval(c, globals_dict, locals_dict)
>   File "", line 1, in <module>
>   File "<decorator-gen-42>", line 2, in button_immediate_install
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 449, in 
> button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 542, in 
> _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 791, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 852, in convert_xml_import
>    obj.parse(doc.getroot(), mode=mode)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 751, in parse
>     exc_info[2]
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 744, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 465, in _tag_menuitem
>     action_type, action_id = self.model_id_get(a_action)
>   File "/opt/odoo/odoo11/odoo/tools/convert.py", line 733, in model_id_get
>     return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, 
> raise_if_not_found=raise_if_not_found)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
>     return self.xmlid_lookup(xmlid)[1:3]
>   File "<decorator-gen-21>", line 2, in xmlid_lookup
>   File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
>     raise ValueError('External ID not found in the system: %s' % xmlid)
> ValueError: <class 'odoo.tools.convert.ParseError'>: "External ID not found in the system: 
> contract.action_account_analytic_sale_overdue_all
> <menuitem id="menu_contract_sale" name="Contracts" parent="sale.sale_order_menu" 
> action="contract.action_account_analytic_sale_overdue_all" sequence="2" 
> groups="sales_team.group_sale_salesman"/>
> /opt/odoo/odoo11/addons/contract_sale/views/account_analytic_account_view.xml
> 10" while evaluating
> 'records.button_immediate_install()' 

Me podeis orientar por que está provocado el error?
Muchas gracias

**Comment by pedrobaeza** [comment] 2018-09-26 19:23
Hi, I'm not able to reproduce this problem in latest runbot version, so I consider that it has been solved meanwhile, and I'm going to close this issue.

If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there. 

If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo-community.org (in the proper branch). If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Closed as completed by pedrobaeza** 2018-09-26 19:23 UTC
