### ISSUE TITLE
[12] [BUG] Contract module

### ISSUE THREAD

**Issue by SSanfilippo** [OCA/contract#531] opened 2020-07-03 07:20 UTC
Hi at all,
I had updated the module with the last version and now I get this error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\contract\wizards\contract_manually_create_invoice.py", line 58, in create_invoice
    invoices |= contract.recurring_create_invoice()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5065, in __or__
    return self.union(other)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5074, in union
    raise TypeError("Mixing apples and oranges: %s.union(%s)" % (self, arg))
TypeError: Mixing apples and oranges: account.invoice().union(None)

Can verify this problem and give me a solution?

Best regards,
Simone

**Comment by pedrobaeza** [comment] 2020-07-03 07:27
Can you replicate the problem in the runbot link provided in the README?

**Comment by SSanfilippo** [comment] 2020-07-03 07:35
> Can you replicate the problem in the runbot link provided in the README?

I don't find any link for runbot, but I don't know how create a runbot.

**Comment by pedrobaeza** [comment] 2020-07-03 07:37
See the badge that puts "Try me on runbot" in the upper head of the README file

**Comment by SSanfilippo** [comment] 2020-07-03 07:42
> See the badge that puts "Try me on runbot" in the upper head of the README file
Ok, found it, but I don't have an account for create an instance ... then cannot make one.

**Comment by pedrobaeza** [comment] 2020-07-03 07:43
You don't need to create one, but use:

admin / admin

**Comment by SSanfilippo** [comment] 2020-07-03 07:45
I must use one of version 12? Ok, try.

**Comment by SSanfilippo** [comment] 2020-07-03 07:48
Ok, I tried one in runbot, create a new contract and then manually create invoice. Work fine.

But in my system no :)

**Comment by SSanfilippo** [comment] 2020-07-03 08:19
@pedrobaeza then what I must do? Wait the new version of the module? Use the source code?
Thanks,
Simone

**Comment by pedrobaeza** [comment] 2020-07-03 08:22
You have to check why that problem:

- Extra incompatible modules on top of `contract` module?
- Not latest source code

**Comment by SSanfilippo** [comment] 2020-07-03 08:25
I don't think that I have incompatible modules, before working after update (I have a version very old of the module) don't work.
Try to download the source code and try.
After I copy the latest source, restart odoo service and go in application and update the contract module?

**Comment by pedrobaeza** [comment] 2020-07-03 08:37
Yes, but again check that you don't have modules that depend on this one

**Comment by SSanfilippo** [comment] 2020-07-03 08:43
@pedrobaeza I tried to update with the latest source, but I have always the problem.

**Comment by pedrobaeza** [comment] 2020-07-03 08:52
Sorry to hear that, but I'm afraid the problem is in your side, and we can't do anything in the scope of the issue tracker, as the problem is not in the module, so closing. If you have further evidences that the problem is in the module, please write back.

**Closed as completed by pedrobaeza** 2020-07-03 08:52 UTC
