### ISSUE TITLE
[12.0] [BUG] Invoice not created from the Sale Contract if you moves "Section" line.

### ISSUE THREAD

**Issue by JordiADARIA** [OCA/contract#519] opened 2020-05-20 18:16 UTC
Hi
checked on runbot:

1. create a Sale Contract.
2. add a line with any product
3. add a section just after it
4. Click (on dev mode) on Create Invoice. Well, it's created (warning, section is not there, on invoice)
5. On the contract, you moves section just before the first line.
6. Click on Create Invoice: **nothing happens**. it's not creating the invoice. 

its not creating the invoice even if you moves again the "section line" above. You can create that invoice deleting completely its "section".

I've been checking on log file, even on debug level, but it's not showing any errors.

thanks

**Comment by pedrobaeza** [comment] 2020-07-12 11:39
I'm not able to reproduce this problem. Are you sure you have latest code?

**Comment by JordiADARIA** [comment] 2020-08-03 18:44
Hi Pedro,

yes, downloading the latest code an even checking on runbot...

ill try to record a video.

thanks for your answer

**Comment by pedrobaeza** [comment] 2020-08-12 16:47
Closing meanwhile until a video is provided.

**Closed as completed by pedrobaeza** 2020-08-12 16:47 UTC
